export const CHAT_INIT_END = 'CHAT/SYNC_FINISHED';
export const CHAT_LOADING_START = 'CHAT/LOADING_START';
export const CHAT_LOADING_END = 'CHAT/LOADING_END';
export const GET_CHATS = 'CHAT/GET_CHATS';
export const CHAT_PENDING_START = 'CHAT/PENDING_START';
export const CHAT_PENDING_END = 'CHAT/PENDING_END';
export const CHAT_ADD_MESSAGE = 'CHAT/ADD_MESSAGE';
export const CHAT_MESSAGE_RECEIVED = 'CHAT/MESSAGE_RECEIVED';
