export const INIT_END = 'CHAT/INITIALIZATION_FINISHED';
export const SET_CONNECTED = 'CHAT/CONNECTED';
export const SET_DISCONNECTED = 'CHAT/DISCONNECTED';
export const SET_ACTION = 'CHAT/ACTION';
export const SET_MAIN_WINDOW_ACTION = 'CHAT/MAIN_WINDOW_ACTION';
